import Head from "next/head";
import Louis from "../images/Louis.jpg";
import Navbar from "@/components/organism/Navbar";
import Footer from "@/components/organism/Footer"
import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Hire Job</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className="container">
          <div class={`input-group mb-3 ${styles.inputHead}`}>
            <input
              type="text"
              class={`form-control ${styles.input}`}
              placeholder="Search For Any Skill"
              aria-label="Example text with button addon"
              aria-describedby="button-addon1"
            />
            <button
              class={`btn ${styles.search}`}
              type="button"
              id="button-addon1"
            >
              Search
            </button>
          </div>
          <div className={styles.content}>
            <div class={`row ${styles.data}`}>
              <div class="col-6">
                <div class="row row-cols-auto">
                  <img src={Louis.src} />
                  <div class={`col ${styles.identity}`}>
                    <h4>Louis Tomlinson</h4>
                    <p>Web Development</p>
                    <div className="row">
                      <button type="button" class={styles.skill} disabled>
                        PHP
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        Javascript
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        HTML
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-2 offset-4">
                <button type="button" class={`btn ${styles.open}`}>
                  Lihat Profile
                </button>
              </div>
            </div>
            <div class={`row ${styles.data}`}>
              <div class="col-6">
                <div class="row row-cols-auto">
                  <img src={Louis.src} />
                  <div class={`col ${styles.identity}`}>
                    <h4>Louis Tomlinson</h4>
                    <p>Web Development</p>
                    <div className="row">
                      <button type="button" class={styles.skill} disabled>
                        PHP
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        Javascript
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        HTML
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-2 offset-4">
                <button type="button" class={`btn ${styles.open}`}>
                  Lihat Profile
                </button>
              </div>
            </div>
            <div class={`row ${styles.data}`}>
              <div class="col-6">
                <div class="row row-cols-auto">
                  <img src={Louis.src} />
                  <div class={`col ${styles.identity}`}>
                    <h4>Louis Tomlinson</h4>
                    <p>Web Development</p>
                    <div className="row">
                      <button type="button" class={styles.skill} disabled>
                        PHP
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        Javascript
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        HTML
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-2 offset-4">
                <button type="button" class={`btn ${styles.open}`}>
                  Lihat Profile
                </button>
              </div>
            </div>
            <div class={`row ${styles.data}`}>
              <div class="col-6">
                <div class="row row-cols-auto">
                  <img src={Louis.src} />
                  <div class={`col ${styles.identity}`}>
                    <h4>Louis Tomlinson</h4>
                    <p>Web Development</p>
                    <div className="row">
                      <button type="button" class={styles.skill} disabled>
                        PHP
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        Javascript
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        HTML
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-2 offset-4">
                <button type="button" class={`btn ${styles.open}`}>
                  Lihat Profile
                </button>
              </div>
            </div>
            <div class={`row ${styles.data}`}>
              <div class="col-6">
                <div class="row row-cols-auto">
                  <img src={Louis.src} />
                  <div class={`col ${styles.identity}`}>
                    <h4>Louis Tomlinson</h4>
                    <p>Web Development</p>
                    <div className="row">
                      <button type="button" class={styles.skill} disabled>
                        PHP
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        Javascript
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        HTML
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-2 offset-4">
                <button type="button" class={`btn ${styles.open}`}>
                  Lihat Profile
                </button>
              </div>
            </div>
            <div class={`row ${styles.data}`}>
              <div class="col-6">
                <div class="row row-cols-auto">
                  <img src={Louis.src} />
                  <div class={`col ${styles.identity}`}>
                    <h4>Louis Tomlinson</h4>
                    <p>Web Development</p>
                    <div className="row">
                      <button type="button" class={styles.skill} disabled>
                        PHP
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        Javascript
                      </button>
                      <button type="button" class={styles.skill} disabled>
                        HTML
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-2 offset-4">
                <button type="button" class={`btn ${styles.open}`}>
                  Lihat Profile
                </button>
              </div>
            </div>
          </div>
          <nav aria-label="Page navigation example">
  <ul class='pagination justify-content-center'>
    <li class={`page-item ${styles.pagination}`}>
      <a class={`page-link ${styles.paginationText}`} href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class={`page-item ${styles.pagination}`}><a class={`page-link ${styles.paginationText}`} href="#">1</a></li>
    <li class={`page-item ${styles.pagination}`}><a class={`page-link ${styles.paginationText}`} href="#">2</a></li>
    <li class={`page-item ${styles.pagination}`}><a class={`page-link ${styles.paginationText}`} href="#">3</a></li>
    <li class={`page-item ${styles.pagination}`}>
      <a class={`page-link ${styles.paginationText}`} href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
        </div>
          <Footer />
      </main>
    </>
  );
}
