import Head from "next/head";
import Navbar from "@/components/organism/Navbar";
import Footer from "@/components/organism/Footer"
import ListJob from "@/components/moleculs/ListJob";
import styles from "@/styles/Home.module.scss";
import React from "react";
import axios from "axios";

export default function Home(props) {

  return (
    <>
      <Head>
        <title>Home | Hire Job</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className="container">
          <div class={`input-group mb-3 ${styles.inputHead}`}>
            <input
              type="text"
              class={`form-control ${styles.input}`}
              placeholder="Search For Any Skill"
              aria-label="Example text with button addon"
              aria-describedby="button-addon1"
            />
            <button
              class={`btn ${styles.search}`}
              type="button"
              id="button-addon1"
            >
              Search
            </button>
          </div>
          <ListJob listData={props} />
          <nav aria-label="Page navigation example">
  <ul class='pagination justify-content-center'>
    <li class={`page-item ${styles.pagination}`}>
      <a class={`page-link ${styles.paginationText}`} href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class={`page-item ${styles.pagination}`}><a class={`page-link ${styles.paginationText}`} href="#">1</a></li>
    <li class={`page-item ${styles.pagination}`}><a class={`page-link ${styles.paginationText}`} href="#">2</a></li>
    <li class={`page-item ${styles.pagination}`}><a class={`page-link ${styles.paginationText}`} href="#">3</a></li>
    <li class={`page-item ${styles.pagination}`}>
      <a class={`page-link ${styles.paginationText}`} href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
        </div>
          <Footer />
      </main>
    </>
  );
}


export async function getServerSideProps(context) {
  const job = await axios.get(`${process.env.NEXT_PUBLIC_URL_BACKEND}/v1/user/list`);
  const jobData = job.data
  return{
    props:{
      jobList:jobData,
    }
  }
}